### ISSUE TITLE
Is https://wiki.sagemath.org/Yacop still needed?

### ISSUE THREAD

**Issue by mkoeppe** [cnassau/yacop-sage#1]

**Comment by cnassau** [comment]
Thanks for bringing this up, I had comlpletely forgotten about that wiki page: I probably created it for the Sage days #10 event in Seatlle and now added a note at the top of it.

As to whether this page is necessary: I don't know. It seems quite "normal" to me that out-dated wiki pages remain on the site, unless there is enough activity going on to keep it current. I guess I would just leave it to rot away but if you feel the wiki should be cleaned up during migration to github you can also just delete it.

**Comment by mkoeppe** [comment]
OK, I'll delete the wiki page then. 
A current link to your package is in https://trac.sagemath.org/ticket/31164
